apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - openshift-operators-devworkspaceoperatorconfig-devworkspace-operator-config.yaml
  - openshift-operators-subscription-devworkspace-operator.yaml
  - openshift-operators-subscription-web-terminal.yaml
