apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../common
  - openshift-operators-subscription-servicemeshoperator3.yaml

replacements:
  - source:
      kind: ConfigMap
      name: cluster-versions
      fieldPath: data.openshift-service-mesh
    targets:
      - select:
          kind: Subscription
          name: servicemeshoperator3
        fieldPaths:
          - spec.channel