apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: config
spec:
  config:
    nodeSelector:
      node-role.kubernetes.io/infra: ""
    tolerations: 
    - key: node-role.kubernetes.io/infra
      operator: Exists
  pruner:
    keep: 5
    resources:
      - pipelinerun
      - taskrun
    schedule: "0 * * * *"
