apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-clusterrole-odhdashboardconfig-admin.yaml
  - cluster-crb-datascienceclusters.datasciencecluster.opendatahub.io-v1-admin-openshift-gitops-argocd-application-controller.yaml
  - cluster-datasciencecluster-default-dsc.yaml
  - cluster-namespace-redhat-ods-applications.yaml
  - cluster-namespace-redhat-ods-operator.yaml
  - redhat-ods-applications-configmap-notebook-controller-culler-config.yaml
  - redhat-ods-applications-odhdashboardconfig-odh-dashboard-config.yaml
  - redhat-ods-applications-rb-odhdashboardconfig-admin-openshift-gitops-argocd-application-controller.yaml
  - redhat-ods-operator-operatorgroup-rhods-operator.yaml
  - redhat-ods-operator-subscription-rhods-operator.yaml
