apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager-operator-operatorgroup-openshift-cert-manager-operator.yaml
  - cert-manager-operator-subscription-openshift-cert-manager-operator.yaml
  - cert-manager-rb-edit-openshift-gitops-argocd-application-controller.yaml
  - cluster-namespace-cert-manager.yaml
  - cluster-namespace-cert-manager-operator.yaml
