apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../common
  - cert-manager-operator-operatorgroup-openshift-cert-manager-operator.yaml
  - cert-manager-operator-subscription-openshift-cert-manager-operator.yaml
  - cluster-crb-clusterissuers.cert-manager.io-v1-edit-openshift-gitops-openshift-gitops-argocd-application.yaml
  - cluster-certmanager-cluster.yaml
  - cluster-namespace-cert-manager-operator.yaml
  - openshift-gitops-configmap-clusterissuer-cluster.yaml
  - openshift-gitops-configmap-openshift-config-certificate-api.yaml
  - openshift-gitops-configmap-openshift-ingress-certificate-ingress.yaml
  - openshift-gitops-job-create-cluster-cert-manager-resources.yaml
  - openshift-gitops-job-update-cluster-apiserver-cluster.yaml
  - openshift-gitops-job-update-openshift-ingress-operator-ingresscontroller-default.yaml

replacements:
  - source:
      kind: ConfigMap
      name: cluster-versions
      fieldPath: data.cert-manager
    targets:
      - select:
          kind: Subscription
          name: openshift-cert-manager-operator
        fieldPaths:
          - spec.channel