apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: LokiStack
      name: logging-loki
    patch: |-
      - op: replace
        path: /spec/size
        value: 1x.medium