apiVersion: v1
kind: ConfigMap
metadata:
  name: machineautoscaler
  namespace: openshift-gitops
data:
  machineautoscaler.yaml: |
    apiVersion: autoscaling.openshift.io/v1beta1
    kind: MachineAutoscaler
    metadata:
      name: machineautoscaler
      namespace: openshift-machine-api
    spec:
      maxReplicas: 2
      minReplicas: 0
      scaleTargetRef:
        apiVersion: machine.openshift.io/v1beta1
        kind: MachineSet
        name: machineset
