apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-namespace-developer-gitops.yaml
  - developer-gitops-rb-argocds.argoproj.io-v1beta1-admin-openshift-gitops-argocd-application-controller.yaml
  - developer-gitops-argocd-argocd.yaml
