apiVersion: v1
baseDomain: $RHDP_TOP_LEVEL_ROUTE53_DOMAIN
metadata:
  name: $CLUSTER_NAME
controlPlane:
  name: master
  platform:
    aws:
      type: m6i.2xlarge
platform:
  aws:
    region: $AWS_DEFAULT_REGION
pullSecret: '$RHOCM_PULL_SECRET'
sshKey: '$SSH_KEY'
