apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster
  namespace: openshift-gitops
spec:
  generators:
  - list:
      # Comment / Uncomment the ArgoCD applications you don't want / want to install
      elements:
      - item: cert-manager
      - item: cluster-images-registry
      - item: cluster-ingress
      - item: cluster-monitoring
      - item: cluster-oauth
      - item: cluster-observability
      - item: loki      
      - item: network-observability
      # - item: nfd
      - item: openshift-builds
      - item: openshift-console
      - item: openshift-data-foundation
      - item: openshift-gitops
      - item: openshift-logging
      - item: openshift-operators
      - item: openshift-pipelines
      - item: openshift-serverless
      - item: openshift-service-mesh
      - item: opentelemetry
      - item: sealed-secrets
      - item: tempo
      - item: user-workload-monitoring
      - item: webterminal
  template:
    metadata:
      finalizers:
      - resources-finalizer.argocd.argoproj.io/background
      name: '{{item}}'
    spec:
      project: default
      source:
        repoURL: https://gitlab.consulting.redhat.com/openshift-toolkit/ocp-open-env-install-tool.git
        path: argocd/{{item}}/overlays/default
        targetRevision: modularization
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      ignoreDifferences:
      - group: operator.openshift.io
        kind: IngressController
        name: default
        jsonPointers:
        - /spec/defaultCertificate
