apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster
  namespace: openshift-gitops
spec:
  generators:
    - list:
      # Comment / Uncomment the ArgoCD applications you don't want / want to install
        elements:
          - branch: master
            item: cert-manager
          - branch: master
            item: cluster-autoscaler
          - branch: master
            item: cluster-images-registry
           # DON'T COMMENT cluster-ingress or it could break other modules installation!
          - branch: master
            item: cluster-ingress
          - branch: master
            item: cluster-monitoring
          - branch: master
            item: cluster-network
          # DON'T COMMENT cluster-oauth in order to get the admin access to the cluster!
          - branch: master
            item: cluster-oauth
          - branch: master
            item: cluster-observability
        # - branch: master
        #   item: developer-gitops
          - branch: master
            item: loki
          - branch: master
            item: network-observability
          - branch: master
            item: nfd
        # - branch: master
        #   item: nfs
          - branch: master
            item: openshift-builds
          # DON'T COMMENT openshift-config or it could break other modules installation!
          - branch: master
            item: openshift-config
          - branch: master
            item: openshift-data-foundation
        # NEVER COMMENT OR REMOVE openshift-gitops otherwise most of modules will fail to be installed!
          - branch: master
            item: openshift-gitops-admin-config
          - branch: master
            item: openshift-logging
          # DON'T COMMENT openshift-operators or it could break other modules installation!
          - branch: master
            item: openshift-operators
          - branch: master
            item: openshift-pipelines
          - branch: master
            item: opentelemetry
        #  - branch: master
        #    item: sealed-secrets
          - branch: master
            item: tempo
          - branch: master
            item: user-workload-monitoring
          - branch: master
            item: webterminal
  template:
    metadata:
      finalizers:
        - resources-finalizer.argocd.argoproj.io/background
      name: '{{item}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/lautou/ocp-open-env-install-tool.git
        path: argocd/{{item}}/overlays/default
        targetRevision: '{{branch}}'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      ignoreDifferences:
        - group: operator.openshift.io
          kind: IngressController
          name: default
          jsonPointers:
            - /spec/defaultCertificate
        - group: ""
          kind: ConfigMap
          name: cluster-versions
          jsonPointers:
            - /metadata/labels
            - /metadata/annotations
            - /metadata/ownerReferences
