apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../gitops-bases/core
  - ../../gitops-bases/storage/full-aws-lean
  - ../../gitops-bases/logging/pico
  - ../../gitops-bases/netobserv/default