apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-crb-tektonconfigs.operator.tekton.dev-v1alpha1-edit-openshift-gitops-openshift-gitops-argocd-application-controller.yaml
  - cluster-tektonconfig-config.yaml
#  - openshift-gitops-job-enable-pipelines-console-plugin.yaml
#  - openshift-gitops-job-disable-pipelines-console-plugin.yaml
  - openshift-operators-subscription-openshift-pipelines-operator.yaml
