apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kube-system-rb-edit-openshift-gitops-openshift-gitops-argocd-application-controller.yaml
  - sealed-secrets-controller-0.27.1.yaml 
