apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-namespace-openshift-ingress.yaml # Required for Cert-Manager Certificate resource creation for ingress
  - openshift-ingress-operator-ingresscontroller-default.yaml 
