apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-namespace-openshift-nfd.yaml
  - openshift-nfd-nodefeaturediscovery-nfd-instance.yaml
  - openshift-nfd-operatorgroup-openshift-nfd.yaml
  - openshift-nfd-subscription-nfd.yaml
