apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-clusterrole-delete-project.yaml
  - cluster-clusterrole-edit-crd.yaml
  - cluster-crb-delete-project-openshift-gitopsopenshift-gitops-argocd-application-controller.yaml
  - cluster-crb-edit-crd-openshift-gitops-openshift-gitops-argocd-application-controller.yaml
  - cluster-crb-gitopsservices.pipelines.openshift.io-v1alpha1-edit-openshift-gitops-openshift-gitops-argocd-application-controller.yaml
  - cluster-gitopsservice-cluster.yaml
  - cluster-group-cluster-admins.yaml
  - openshift-gitops-argocd-openshift-gitops.yaml
  #- openshift-gitops-job-enable-gitops-console-plugin.yaml
