apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-crb-cluster-image-registry-operator-openshift-gitops-openshift-gitops-argocd-application-controller.yaml
  - cluster-imagepruner-cluster.yaml
  - cluster-imageregistry-config-cluster.yaml
