apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-acs-secured
  namespace: openshift-gitops
spec:
  generators:
    - list:
        elements:
          - branch: master
            item: rhacs
  template:
    metadata:
      name: '{{item}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/lautou/ocp-open-env-install-tool.git
        path: components/rhacs/overlays/secured
        targetRevision: '{{branch}}'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      ignoreDifferences:
        - group: ""
          kind: ConfigMap
          name: cluster-versions
          jsonPointers:
            - /metadata/labels
            - /metadata/annotations
            - /metadata/ownerReferences