apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster
  namespace: openshift-gitops
spec:
  source:
    repoURL: https://gitlab.consulting.redhat.com/ltourrea/ocp-open-env-install-tool