apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnDeploymentConfig
metadata:
  name: deploy-config
  namespace: open-cluster-management-hub
spec:
  nodePlacement:
    nodeSelector:
      node-role.kubernetes.io/infra: ''
    tolerations:
      - key: node-role.kubernetes.io/infra
        operator: Exists