apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../common
  - cluster-namespace-openshift-builds.yaml
  - openshift-builds-operatorgroup-openshift-builds-operator.yaml  
  - openshift-builds-subscription-openshift-builds-operator.yaml 
  - openshift-gitops-job-check-and-wait-openshift-pipelines.yaml
  - openshift-gitops-job-delete-openshift-builds-resources.yaml

replacements:
  - source:
      kind: ConfigMap
      name: cluster-versions
      fieldPath: data.openshift-builds
    targets:
      - select:
          kind: Subscription
          name: openshift-builds-operator
        fieldPaths:
          - spec.channel