apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-namespace-rhacs-operator.yaml
  - cluster-namespace-stackrox.yaml
  - rhacs-operator-operatorgroup-rhacs-operator.yaml
  - rhacs-operator-subscription-rhacs-operator.yaml