apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../full-aws-base
patches:
  - target:
      kind: StorageCluster
      name: ocs-storagecluster
    patch: |-
      - op: replace
        path: /spec/resourceProfile
        value: lean