apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-namespace-openshift-opentelemetry-operator.yaml 
  - openshift-opentelemetry-operator-operatorgroup-openshift-opentelemetry-operator.yaml 
  - openshift-opentelemetry-operator-subscription-opentelemetry-product.yaml
