resources:
- application-cluster.yaml

patches:
- patch: |-
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: cluster
      namespace: openshift-gitops
    spec:
      source:
        repoURL: https://gitlab.consulting.redhat.com/openshift-toolkit/ocp-open-env-install-tool
