apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-namespace-nfsprovisioner-operator.yaml
  - nfsprovisioner-operator-nfsprovisioner-nfsprovisioner-sample.yaml
  - openshift-operators-subscription-nfs-provisioner-operator.yaml
