apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-crb-flowcollectors.flows.netobserv.io-v1beta2-admin-openshift-gitops-argocd-application-controller.yaml
  - cluster-flowcollector-cluster.yaml
  - cluster-namespace-openshift-netobserv-operator.yaml
  - openshift-netobserv-operator-operatorgroup-openshift-netobserv-operator.yaml
  - openshift-netobserv-operator-subscription-netobserv-operator.yaml
