apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../common
  - cluster-crb-flowcollectors.flows.netobserv.io-v1beta2-admin-openshift-gitops-openshift-gitops-argocd-application-controller.yaml
  - cluster-flowcollector-cluster.yaml
  - cluster-namespace-openshift-netobserv-operator.yaml
  - openshift-netobserv-operator-operatorgroup-openshift-netobserv-operator.yaml
  - openshift-netobserv-operator-subscription-netobserv-operator.yaml

replacements:
  - source:
      kind: ConfigMap
      name: cluster-versions
      fieldPath: data.network-observability
    targets:
      - select:
          kind: Subscription
          name: openshift-netobserv-operator
        fieldPaths:
          - spec.channel