apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - openshift-storage-driver-openshift-storage.cephfs.csi.ceph.com.yaml
  - openshift-storage-driver-openshift-storage.rbd.csi.ceph.com.yaml
  - openshift-storage-storagecluster-ocs-storagecluster.yaml
