apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../gitops-bases/applicationset-cluster-core-components.yaml
  - ../../gitops-bases/applicationset-cluster-storage-full.yaml