apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-crb-uiplugins.observability.openshift.io-v1alpha1-edit-openshift-gitops-openshift-gitops-argocd-application-controller.yaml
  - cluster-uiplugin-logging.yaml
  - openshift-operators-subscription-cluster-observability-operator.yaml
