apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-clusterrole-delete-project.yaml
  - cluster-crb-delete-project-openshift-gitops-argocd-application-controller.yaml
  - cluster-group-cluster-admins.yaml
  - openshift-gitops-argocd-openshift-gitops.yaml
