apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-clusterrole-edit-crds-admission.yaml
  - cluster-crb-edit-crds-admission-openshift-gitops-argocd-application-controller.yaml
