apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../common
  - cluster-namespace-openshift-kueue-operator.yaml
  - openshift-kueue-operator-operatorgroup-openshift-kueue-operator.yaml  
  - openshift-kueue-operator-subscription-openshift-kueue-operator.yaml

replacements:
  - source:
      kind: ConfigMap
      name: cluster-versions
      fieldPath: data.kueue
    targets:
      - select:
          kind: Subscription
          name: kueue-operator
        fieldPaths:
          - spec.channel