apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../common
  - cluster-namespace-openshift-tempo-operator.yaml
  - openshift-tempo-operator-operatorgroup-openshift-tempo-operator.yaml
  - openshift-tempo-operator-subscription-tempo-product.yaml

replacements:
  - source:
      kind: ConfigMap
      name: cluster-versions
      fieldPath: data.tempo
    targets:
      - select:
          kind: Subscription
          name: openshift-tempo-operator
        fieldPaths:
          - spec.channel