apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - cluster-clusterrole-edit-klusterlet.yaml
  - cluster-clusterrole-klusterlet-bootstrap-kubeconfig.yaml
  - cluster-clusterrole-klusterlet.yaml
  - cluster-clusterrole-open-cluster-management-klusterlet-admin-aggregate-clusterrole.yaml
  - cluster-crb-edit-klusterlet-openshift-gitops-openshift-gitops-argocd-application-controller.yaml
  - cluster-crb-klusterlet.yaml
  - cluster-crd-klusterlets.operator.open-cluster-management.io.yaml
#  - cluster-klusterlet-klusterlet.yaml
  - cluster-namespace-open-cluster-management-agent.yaml
#  - open-cluster-management-agent-deploy-klusterlet.yaml
  - open-cluster-management-agent-sa-klusterlet.yaml
  - open-cluster-management-agent-secret-open-cluster-management-image-pull-credentials.yaml
